"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SettingType = exports.PenMessageType = exports.Dot = exports.PenController = void 0;
var PenController_1 = require("./PenCotroller/PenController");
exports.PenController = PenController_1.default;
var Dot_1 = require("./API/Dot");
exports.Dot = Dot_1.default;
var PenMessageType_1 = require("./API/PenMessageType");
exports.PenMessageType = PenMessageType_1.default;
Object.defineProperty(exports, "SettingType", { enumerable: true, get: function () { return PenMessageType_1.SettingType; } });
