const CMD = {
  VERSION_REQUEST: 0x01,
  VERSION_RESPONSE: 0x81,

  PASSWORD_REQUEST: 0x02,
  PASSWORD_RESPONSE: 0x82,

  PASSWORD_CHANGE_REQUEST: 0x03,
  PASSWORD_CHANGE_RESPONSE: 0x83,

  SETTING_INFO_REQUEST: 0x04,
  SETTING_INFO_RESPONSE: 0x84,

  LOW_BATTERY_EVENT: 0x61,
  SHUTDOWN_EVENT: 0x62,

  SETTING_CHANGE_REQUEST: 0x05,
  SETTING_CHANGE_RESPONSE: 0x85,

  ONLINE_DATA_REQUEST: 0x11,
  ONLINE_DATA_RESPONSE: 0x91,

  ONLINE_PEN_UPDOWN_EVENT: 0x63,
  ONLINE_PAPER_INFO_EVENT: 0x64,
  ONLINE_PEN_DOT_EVENT: 0x65,
  ONLINE_PEN_ERROR_EVENT: 0x68,

  ONLINE_NEW_PEN_DOWN_EVENT: 0x69,
  ONLINE_NEW_PEN_UP_EVENT: 0x6a,
  ONLINE_NEW_PAPER_INFO_EVENT: 0x6b,
  ONLINE_NEW_PEN_DOT_EVENT: 0x6c,
  ONLINE_NEW_PEN_ERROR_EVENT: 0x6d,

  OFFLINE_NOTE_LIST_REQUEST: 0x21,
  OFFLINE_NOTE_LIST_RESPONSE: 0xa1,

  OFFLINE_PAGE_LIST_REQUEST: 0x22,
  OFFLINE_PAGE_LIST_RESPONSE: 0xa2,

  OFFLINE_DATA_REQUEST: 0x23,
  OFFLINE_DATA_RESPONSE: 0xa3,
  OFFLINE_PACKET_REQUEST: 0x24,
  OFFLINE_PACKET_RESPONSE: 0xa4,

  OFFLINE_DATA_DELETE_REQUEST: 0x25,
  OFFLINE_DATA_DELETE_RESPONSE: 0xa5,

  FIRMWARE_UPLOAD_REQUEST: 0x31,
  FIRMWARE_UPLOAD_RESPONSE: 0xb1,
  FIRMWARE_PACKET_REQUEST: 0x32,
  FIRMWARE_PACKET_RESPONSE: 0xb2,

  PEN_PROFILE_REQUEST: 0x41,
  PEN_PROFILE_RESPONSE: 0xc1,

  // Only Touch and play
  RES_PDS : 0x73,
  REQ_LOG_INFO : 0x74,
  RES_LOG_INFO : 0xF4,
  REQ_LOG_DATA : 0x75,
  RES_LOG_DATA : 0xF5,

}

export default CMD